[JuliaLowering] Treat GlobalRef like an identifier (#61410)
Atop #61372, fix
https://github.com/JuliaLang/JuliaLowering.jl/issues/149. Femtolisp
lowering generally allows GlobalRef in any place a plain identifier
would be allowed. By representing GlobalRef as `K"Identifier"` with a
`mod` attribute and checking `mod` in scope resolution, we can pretty
neatly provide the same functionality (though I won't rule out tweaks
being needed to desugaring or scope resolution on top of this easy
implementation).

Note flisp will sometimes allow a globalref in the position of a local
being declared. I've just disallowed it in this PR.

```
julia> test_mod = Module()
julia> gr_mod = Module()

# local gr = 1
julia> Core.eval(test_mod, Expr(:local, Expr(:(=), GlobalRef(gr_mod, :local_assign), 1)))

julia> gr_mod.local_assign
1

# for gr = 1:3
julia> Core.eval(test_mod, Expr(:for,
                              Expr(:(=), GlobalRef(gr_mod, :for_assign),
                                   Expr(:call, :(:), 1, 3)),
                              Expr(:block, Expr(:call, :println, GlobalRef(gr_mod, :for_assign)))))
1
2
3

julia> gr_mod.for_assign
3

# local gr
julia> Core.eval(test_mod, Expr(:local, GlobalRef(gr_mod, :die)))
[26825] signal 11 (2): Segmentation fault: 11
in expression starting at none:1
jl_gc_small_alloc_inner at ./julia/src/gc-stock.c:751 [inlined]
jl_gc_small_alloc_noinline at ./julia/src/gc-stock.c:792 [inlined]
jl_gc_alloc_ at ./julia/src/gc-stock.c:806
ijl_box_slotnumber at ./julia/src/datatype.c:1580 [inlined]

# function fname(gr); end
julia> Core.eval(test_mod, Expr(:function,
                              Expr(:call, :fname, GlobalRef(gr_mod, :arg)),
                              Expr(:block)))
ERROR: syntax: "anonymous.arg" is not a valid function argument name
```

Also add plenty of tests (some from Claude). Suggestions for more are
welcome.