bugfix for -Dates.CompoundPeriod() (#61282)
This fixes a bug where `-Dates.CompoundPeriod()` threw an error, which
occurred because `-Period[]` returns `Any[]` (which happens because
`Period` is an abstract type):
```jl
julia> -Dates.CompoundPeriod()
ERROR: MethodError: no method matching Dates.CompoundPeriod(::Vector{Any})
The type `Dates.CompoundPeriod` exists, but no method is defined for this combination of argument types when trying to construct it.
```
(This also causes subtraction to fail.)

The PR uses a comprehension instead of `-x.periods` to ensure that a
`Vector{Period}` array is created.

(I noticed this when looking at #61280 by @yakir12, to make sure
`CompoundPeriod()` is an additive identity.)